'use client'


import { Progress } from "@/components/ui/progress"
import { JForm, JFormFields } from '@/jutge-components/formatters/JForm'
import { useAuth } from '@/jutge-components/layouts/court/lib/Auth'
import Page from '@/jutge-components/layouts/court/Page'
import jutge from '@/lib/jutge'
import { offerDownloadFile } from '@/lib/utils'
import { set } from 'date-fns'
import { BotIcon, Languages } from 'lucide-react'
import { useEffect, useState } from 'react'
import { toast } from 'sonner'
import z from 'zod'

export default function ProblemsGenPage() {
    return (
        <Page
            pageContext={{
                title: 'Gen problem',
                menu: 'user',
                current: 'problems',
                subTitle: 'Gen problem',
            }}
        >
            <ProblemsGenView />
        </Page>
    )
}

function ProblemsGenView() {
    //
    const auth = useAuth()

    const [state, setState] = useState<'idle' | 'generating' | 'done'>('idle')
    const [title, setTitle] = useState('Is it prime?')
    const [authorship, setAuthorship] = useState((auth.user?.name || 'Unknown') + ' with JutgeAI')
    const [prompt, setPrompt] = useState('Write a problem where the goal is to read a sequence of numbers and, for each one, tell if it is prime or not. Add a short cute story to the problem about a girl named Clara who loves math.')
    const [language, setLanguage] = useState<string>('en')
    const [solution, setSolution] = useState<string>('Python3')
    const [accept, setAccept] = useState(false)
    const [progress, setProgress] = useState(0)

    useEffect(() => {
        const timer = setTimeout(() => {
            setProgress(old => old <= 99 ? old + 1 : 0)
        }, 500)
        return () => clearTimeout(timer)
    }, [state, progress])

    async function validateForm() {
        let valid = true
        if (title.length < 8) {
            toast.error('Title must be at least 8 characters long')
            valid = false
        }
        return valid
    }

    const fields: JFormFields = {
        header: {
            type: 'free',
            label: '',
            content: (
                <div className="text-sm space-y-2 border rounded-lg p-4 mb-8">
                    <div>
                        <BotIcon size={64} strokeWidth={0.8} className="ml-2" />
                    </div>
                    <p>
                        This page will help you generating a new problem using Jutge<sup>AI</sup>. Please provide
                        the necessary information in the form below and click the &quot;Generate problem&quot; button. TODO: multiple languages and solutions.
                    </p>
                </div>
            ),
        },
        title: {
            type: 'input',
            label: 'Title',
            value: title,
            setValue: setTitle,
            validator: z.string().min(8),
            placeHolder: 'Title of the problem',
        },
        prompt: {
            type: 'textarea',
            label: 'Prompt',
            value: prompt,
            setValue: setPrompt,
            validator: z.string().min(32),
            placeHolder: 'Description of the problem to be generated. Eg: Write a problem where the goal is to read a sequence of numbers and, for each one, tell if it is prime or not. Add a cute story to the problem about a girl named Clara who loves math.',
        },
        authorship: {
            type: 'input',
            label: 'Authorship',
            value: authorship,
            setValue: setAuthorship,
            validator: z.string().min(8),
            placeHolder: 'Authorship of the problem',
        },
        language: {
            type: 'select',
            label: 'Language',
            value: language,
            setValue: setLanguage,
            options: [
                { label: 'Catalan', value: 'ca' },
                { label: 'Spanish', value: 'es' },
                { label: 'English', value: 'en' },
                { label: 'French', value: 'fr' },
                { label: 'German', value: 'de' },
            ],
        },
        solution: {
            type: 'select',
            label: 'Solution',
            value: solution,
            setValue: setSolution,
            options: [
                { label: 'C++', value: 'C++' },
                { label: 'Python3', value: 'Python3' },
                { label: 'Haskell', value: 'Haskell' },
                { label: 'Clojure', value: 'Clojure' },
            ],
        },
        accept: {
            type: 'switch',
            label: <div className='font-normal'>I understand that the problem generated by Jutge<sup>AI</sup> may require further editing and careful review before being published.</div>,
            value: accept,
            setValue: setAccept,
        },
        sep: { type: 'separator' },
        add: {
            type: 'button',
            text: 'Generate',
            icon: <BotIcon />,
            action: genAction,
        },
    }

    function error(msg: string) {
        toast.error(msg)
        return 1
    }

    async function genAction() {
        setState('generating')
        setProgress(0)
        jutge.instructor.problems.generateProblem({
            title,
            author: authorship,
            prompt,
            language,
            proglang: solution,
            model: 'openai/gpt-5-mini',
        }).then((download) => {
            setState('done')
            new Audio('/notification.mp3').play()
            toast.success('Problem generated successfully!')
            offerDownloadFile(download, download.name)
        }).catch((e) => {
            toast.error('Error generating problem: ' + e.message)
            setState('idle')
        })
    }

    if (state === 'idle') {
        return <JForm fields={fields} />
    } else if (state === 'generating') {
        return (
            <div className="border rounded-lg p-8 mb-4 flex flex-col justify-center items-center gap-4">
                <div className="text-sm">Generating problem...</div>
                <BotIcon size={96} className="animate-pulse" strokeWidth={0.5} />
                <Progress value={progress} className="w-96" />
                <div className="text-sm">Please wait</div>
            </div>
        )
    } else {
        return <div>Done!</div>
    }
}
