'use client'

import { BotIcon, BotMessageSquareIcon, HomeIcon } from 'lucide-react'
import Link from 'next/link'
import { useState } from 'react'
import { toast } from 'sonner'
import z from 'zod'
import { JForm, JFormFields } from '../../../components/formatters/JForm'
import { useAuth } from '../../../components/layouts/court/lib/Auth'
import Page from '../../../components/layouts/court/Page'
import { Button } from '../../../components/ui/button'
import jutge from '../../../lib/jutge'

export default function ProblemsGenPage() {
    return (
        <Page
            pageContext={{
                title: 'Generate problem',
                menu: 'user',
                current: 'problems',
                subTitle: 'Generate problem',
            }}
        >
            <ProblemsGenView />
        </Page>
    )
}

function ProblemsGenView() {
    //
    const auth = useAuth()

    const [state, setState] = useState<'idle' | 'done'>('idle')
    const [title, setTitle] = useState('Is it prime?')
    const [prompt, setPrompt] = useState(
        'Write a problem where the goal is to read a sequence of numbers and, for each one, tell if it is prime or not. Add a short cute story to the problem about a girl named Clara who loves math.',
    )
    const [model, setModel] = useState('google/gemini-2.5-flash-lite')
    const [accept, setAccept] = useState(true)

    const fields: JFormFields = {
        header: {
            type: 'free',
            label: '',
            content: (
                <div className="text-sm space-y-2 border rounded-lg p-4 mb-8">
                    <div>
                        <BotIcon size={64} strokeWidth={0.8} className="ml-2" />
                    </div>
                    <p>
                        This page will help you generating a new problem using Jutge<sup>AI</sup>.
                    </p>
                    <p>
                        The problem will be generated in English, Catalan and Spanish and will
                        include solutions in Python and C++. A README.md file will be also generated
                        with comments and cost estimates.
                    </p>
                    <p>
                        The generated problem will be sent to your email address. It may take a few
                        minutes depending on the model selected.
                    </p>
                </div>
            ),
        },
        title: {
            type: 'input',
            label: 'Title',
            value: title,
            setValue: setTitle,
            validator: z.string().min(8),
            placeHolder: 'Title of the problem',
        },
        prompt: {
            type: 'textarea',
            label: 'Prompt',
            value: prompt,
            setValue: setPrompt,
            validator: z.string().min(32),
            placeHolder:
                'Description of the problem to be generated. Eg: Write a problem where the goal is to read a sequence of numbers and, for each one, tell if it is prime or not. Add a cute story to the problem about a girl named Clara who loves math.',
            rows: 6,
        },
        model: {
            type: 'select',
            label: 'Model',
            value: model,
            setValue: (v: string | null) => setModel(v || ''),
            options: [
                { value: 'google/gemini-2.5-flash-lite', label: 'Gemini 2.5 Flash Lite' },
                { value: 'google/gemini-2.5-flash', label: 'Gemini 2.5 Flash' },
                { value: 'openai/gpt-5-mini', label: 'GPT-5 Mini' },
                { value: 'openai/gpt-5-nano', label: 'GPT-5 Nano' },
            ],
        },
        accept: {
            type: 'switch',
            label: (
                <div className="font-normal">
                    I understand that the problem generated by Jutge<sup>AI</sup> may require
                    further editing and careful review before being published.
                </div>
            ),
            value: accept,
            setValue: setAccept,
            validator: z.literal(true, {
                errorMap: () => ({ message: 'You must accept the terms to proceed' }),
            }),
        },
        sep: { type: 'separator' },
        add: {
            type: 'button',
            text: 'Generate',
            icon: <BotIcon />,
            action: genAction,
        },
    }

    function error(msg: string) {
        toast.error(msg)
        return 1
    }

    async function genAction() {
        const r = await jutge.instructor.problems.generateProblemWithJutgeAI({
            title,
            prompt,
            model,
        })
        setState('done')
        console.log(r)
    }

    if (state === 'idle') {
        return <JForm fields={fields} />
    } else {
        return (
            <div className="border rounded-lg p-8 mb-4 flex flex-col justify-center items-center gap-4">
                <div className="text-sm">
                    Your problem is being generated by Jutge<sup>AI</sup>.
                </div>
                <BotMessageSquareIcon size={96} strokeWidth={0.5} />
                <div className="text-sm">
                    The generated problem will be sent to your email address (
                    <code className="text-xs">{auth.user!.email}</code>).
                </div>
                <div className="text-sm">
                    It may take a few minutes depending on the model selected.
                </div>
                <Link href="/" className="mt-8">
                    <Button>
                        <HomeIcon className="mr-2" size={16} />
                        Go to home
                    </Button>
                </Link>
            </div>
        )
    }
}
